project:
  type: website
  output-dir: docs

website:
  title: "Lamia's Research Notebook"
  site-url: "https://lghub-t.github.io/myblog"
  
  navbar:
    left:
      - text: "Home"
        href: index.qmd

      - text: "Macroeconometrics"
        menu:
          - text: "Business Cycle Filters"
            href: filters.qmd
          - text: "Basic VAR Modeling"
            href: var_modeling.qmd
          - text: "Max-share Identification"
            href: maxshare.qmd
          - text: "Bayesian Models"
            href: bayesian.qmd

      - text: "Data Science"
        menu:
          - text: "Factorial Analysis Methods"
            href: factorial.qmd
          - text: "Time Series in R"
            href: timeseries.qmd

      - text: "Macroeconomic Theory"
        menu:
          - text: "Growth Theory"
            href: growth.qmd

      - text: "Other Topics"
        menu:
          - text: "NetLogo Tutorial"
            href: netlogo.qmd

      - text: "Teaching"
        menu:
          - text: "Analyse de données"
            href: analyse_donnees.qmd
          - text: "Théorie des probabilités"
            href: proba.qmd
          - text: "Statistique inférentielle"
            href: inference.qmd

      - text: "Projects"
        href: projects.qmd

      - text: "Research"
        href: papers.qmd

      - text: "About"
        href: about.qmd
